// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB02YESY_hC_vOFlkSpcuCIKBynKjxzZGk',
    appId: '1:950981040492:web:335765dd8240aaac7c7b49',
    messagingSenderId: '950981040492',
    projectId: 'chatapp-fc925',
    authDomain: 'chatapp-fc925.firebaseapp.com',
    storageBucket: 'chatapp-fc925.firebasestorage.app',
    measurementId: 'G-WTVLDRVD62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXV2MbUSAhyrIk7OzJGoilHOurtePMQ6Q',
    appId: '1:950981040492:android:d7050e1e73208e6b7c7b49',
    messagingSenderId: '950981040492',
    projectId: 'chatapp-fc925',
    storageBucket: 'chatapp-fc925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_xeBnmwJKZf2lCEPMY7P80i0B-fS8z4s',
    appId: '1:950981040492:ios:590369e21081c4b87c7b49',
    messagingSenderId: '950981040492',
    projectId: 'chatapp-fc925',
    storageBucket: 'chatapp-fc925.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_xeBnmwJKZf2lCEPMY7P80i0B-fS8z4s',
    appId: '1:950981040492:ios:590369e21081c4b87c7b49',
    messagingSenderId: '950981040492',
    projectId: 'chatapp-fc925',
    storageBucket: 'chatapp-fc925.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB02YESY_hC_vOFlkSpcuCIKBynKjxzZGk',
    appId: '1:950981040492:web:e3610d32809a025c7c7b49',
    messagingSenderId: '950981040492',
    projectId: 'chatapp-fc925',
    authDomain: 'chatapp-fc925.firebaseapp.com',
    storageBucket: 'chatapp-fc925.firebasestorage.app',
    measurementId: 'G-8SQH8EL2B8',
  );
}
